# http://travis-ci.org/#!/astraw/stdeb
language: python
python:
    - 2.7
before_install:
    - sudo apt-get update
    - sudo apt-get install python-all-dev debhelper python-setuptools apt-file
install:
    # Use system python, not virtualenv, to use Debian/Ubuntu patches
    - deactivate # the virtualenv

    # Build a .deb file
    - python setup.py --command-packages=stdeb.command bdist_deb

    # Install it as a normal package.
    - sudo dpkg -i deb_dist/*.deb
script:
    - ./test.sh
    - ./test-pypi-install.sh
branches:
  except:
    - pristine-tar
    - old-stable
    - zooko
